#############################################################################
# Makefile for building: tetris
# Generated by qmake (2.01a) (Qt 4.8.0) on: Tue Jan 10 14:06:25 2012
# Project:  tetris.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile tetris.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc -Ibuild
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/dialogs.cpp \
		src/figure.cpp \
		src/gamefield.cpp \
		src/generator.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/nextfiguredisplay.cpp \
		src/scorewidget.cpp \
		src/pplace.cpp \
		src/scoreboard.cpp build/moc_dialogs.cpp \
		build/moc_gamefield.cpp \
		build/moc_generator.cpp \
		build/moc_mainwindow.cpp \
		build/moc_nextfiguredisplay.cpp \
		build/moc_scorewidget.cpp \
		build/moc_scoreboard.cpp
OBJECTS       = build/dialogs.o \
		build/figure.o \
		build/gamefield.o \
		build/generator.o \
		build/main.o \
		build/mainwindow.o \
		build/nextfiguredisplay.o \
		build/scorewidget.o \
		build/pplace.o \
		build/scoreboard.o \
		build/moc_dialogs.o \
		build/moc_gamefield.o \
		build/moc_generator.o \
		build/moc_mainwindow.o \
		build/moc_nextfiguredisplay.o \
		build/moc_scorewidget.o \
		build/moc_scoreboard.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		tetris.pro
QMAKE_TARGET  = tetris
DESTDIR       = 
TARGET        = tetris

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: tetris.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile tetris.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile tetris.pro

dist: 
	@$(CHK_DIR_EXISTS) build/tetris1.0.0 || $(MKDIR) build/tetris1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/tetris1.0.0/ && $(COPY_FILE) --parents src/dialogs.h src/enums.h src/figure.h src/gamefield.h src/generator.h src/mainwindow.h src/nextfiguredisplay.h src/scorewidget.h src/pplace.h src/scoreboard.h build/tetris1.0.0/ && $(COPY_FILE) --parents src/dialogs.cpp src/figure.cpp src/gamefield.cpp src/generator.cpp src/main.cpp src/mainwindow.cpp src/nextfiguredisplay.cpp src/scorewidget.cpp src/pplace.cpp src/scoreboard.cpp build/tetris1.0.0/ && (cd `dirname build/tetris1.0.0` && $(TAR) tetris1.0.0.tar tetris1.0.0 && $(COMPRESS) tetris1.0.0.tar) && $(MOVE) `dirname build/tetris1.0.0`/tetris1.0.0.tar.gz . && $(DEL_FILE) -r build/tetris1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_dialogs.cpp build/moc_gamefield.cpp build/moc_generator.cpp build/moc_mainwindow.cpp build/moc_nextfiguredisplay.cpp build/moc_scorewidget.cpp build/moc_scoreboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_dialogs.cpp build/moc_gamefield.cpp build/moc_generator.cpp build/moc_mainwindow.cpp build/moc_nextfiguredisplay.cpp build/moc_scorewidget.cpp build/moc_scoreboard.cpp
build/moc_dialogs.cpp: src/dialogs.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/dialogs.h -o build/moc_dialogs.cpp

build/moc_gamefield.cpp: src/mainwindow.h \
		src/enums.h \
		src/figure.h \
		src/gamefield.h \
		src/pplace.h \
		src/gamefield.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gamefield.h -o build/moc_gamefield.cpp

build/moc_generator.cpp: src/figure.h \
		src/gamefield.h \
		src/mainwindow.h \
		src/enums.h \
		src/pplace.h \
		src/generator.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/generator.h -o build/moc_generator.cpp

build/moc_mainwindow.cpp: src/enums.h \
		src/mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o build/moc_mainwindow.cpp

build/moc_nextfiguredisplay.cpp: src/gamefield.h \
		src/mainwindow.h \
		src/enums.h \
		src/figure.h \
		src/pplace.h \
		src/nextfiguredisplay.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/nextfiguredisplay.h -o build/moc_nextfiguredisplay.cpp

build/moc_scorewidget.cpp: src/enums.h \
		src/scorewidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/scorewidget.h -o build/moc_scorewidget.cpp

build/moc_scoreboard.cpp: src/scoreboard.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/scoreboard.h -o build/moc_scoreboard.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/dialogs.o: src/dialogs.cpp src/dialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dialogs.o src/dialogs.cpp

build/figure.o: src/figure.cpp src/figure.h \
		src/gamefield.h \
		src/mainwindow.h \
		src/enums.h \
		src/pplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/figure.o src/figure.cpp

build/gamefield.o: src/gamefield.cpp src/gamefield.h \
		src/mainwindow.h \
		src/enums.h \
		src/figure.h \
		src/pplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gamefield.o src/gamefield.cpp

build/generator.o: src/generator.cpp src/generator.h \
		src/figure.h \
		src/gamefield.h \
		src/mainwindow.h \
		src/enums.h \
		src/pplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/generator.o src/generator.cpp

build/main.o: src/main.cpp src/enums.h \
		src/mainwindow.h \
		src/gamefield.h \
		src/figure.h \
		src/pplace.h \
		src/dialogs.h \
		src/nextfiguredisplay.h \
		src/generator.h \
		src/scorewidget.h \
		src/scoreboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/enums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindow.o src/mainwindow.cpp

build/nextfiguredisplay.o: src/nextfiguredisplay.cpp src/nextfiguredisplay.h \
		src/gamefield.h \
		src/mainwindow.h \
		src/enums.h \
		src/figure.h \
		src/pplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/nextfiguredisplay.o src/nextfiguredisplay.cpp

build/scorewidget.o: src/scorewidget.cpp src/scorewidget.h \
		src/enums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/scorewidget.o src/scorewidget.cpp

build/pplace.o: src/pplace.cpp src/pplace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/pplace.o src/pplace.cpp

build/scoreboard.o: src/scoreboard.cpp src/scoreboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/scoreboard.o src/scoreboard.cpp

build/moc_dialogs.o: build/moc_dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dialogs.o build/moc_dialogs.cpp

build/moc_gamefield.o: build/moc_gamefield.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_gamefield.o build/moc_gamefield.cpp

build/moc_generator.o: build/moc_generator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_generator.o build/moc_generator.cpp

build/moc_mainwindow.o: build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindow.o build/moc_mainwindow.cpp

build/moc_nextfiguredisplay.o: build/moc_nextfiguredisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_nextfiguredisplay.o build/moc_nextfiguredisplay.cpp

build/moc_scorewidget.o: build/moc_scorewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_scorewidget.o build/moc_scorewidget.cpp

build/moc_scoreboard.o: build/moc_scoreboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_scoreboard.o build/moc_scoreboard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

